cc_library(
  name = "zookeeper_cc_util",
  srcs = ["zookeeper_cc_util.cc"],
  hdrs = ["zookeeper_cc_util.h"],
  visibility = ["//visibility:public"],
  deps = [
    "@zookeeper//:zookeeper_mt",
  ],
)
