new_http_archive(
    name = "zookeeper",
    url = "http://apache.mirror.cdnetworks.com/zookeeper/zookeeper-3.4.9/zookeeper-3.4.9.tar.gz",
    sha256 = "e7f340412a61c7934b5143faef8d13529b29242ebfba2eba48169f4a8392f535",
    strip_prefix = "zookeeper-3.4.9/src/c",
    build_file = "BUILD.zookeeper",
)

local_repository(
    name = "tf_serving",
    path = "serving",
)
local_repository(
    name = "org_tensorflow",
    path = "serving/tensorflow",
)

# TensorFlow depends on "io_bazel_rules_closure" so we need this here.
# Needs to be kept in sync with the same target in TensorFlow's and 
# TensorFlow Serving's WORKSPACE files.
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "60fc6977908f999b23ca65698c2bb70213403824a84f7904310b6000d78be9ce",
    strip_prefix = "rules_closure-5ca1dab6df9ad02050f7ba4e816407f88690cf7d",
    urls = [
        "http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/rules_closure/archive/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz",  # 2017-02-03
        "https://github.com/bazelbuild/rules_closure/archive/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz",
    ],
)

load("@tf_serving//tensorflow_serving:workspace.bzl", "tf_serving_workspace")
tf_serving_workspace()

load("@org_tensorflow//tensorflow:workspace.bzl", "check_version")
check_version("0.4.2")
